"""Third initial migration.

Revision ID: 92c8e9dc1e2e
Revises: 644396b366f2
Create Date: 2020-12-14 16:27:57.229909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c8e9dc1e2e'
down_revision = '644396b366f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('invite', sa.String(length=256), nullable=True))
    op.add_column('budget', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('expense', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('item', sa.Column('name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    op.drop_column('expense', 'name')
    op.drop_column('budget', 'name')
    op.drop_column('budget', 'invite')
    # ### end Alembic commands ###
